# Generated by Django 2.2.4 on 2019-08-28 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='Frontend',
        ),
    ]
