# Generated by Django 2.2.4 on 2019-09-02 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('frontend', '0002_auto_20190828_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontend',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='frontend', to=settings.AUTH_USER_MODEL),
        ),
    ]
